/** @file

MODULE						: InterPLastRunLevH263Impl

TAG								: IPLRLH263I

FILE NAME					: InterPLastRunLevH263Impl.h

DESCRIPTION				: A class to implement a last-run-level codec on the 
										2-D quantised dct coeffs of an Inter-P coded 8x8 block 
										as defined in the H.263 standard. It implements the 
										IRunLengthCodec interface.

REVISION HISTORY	:
									: 

COPYRIGHT					: 

RESTRICTIONS			: 
===========================================================================
*/
#ifndef _INTERPLASTRUNLEVH263IMPL_H
#define _INTERPLASTRUNLEVH263IMPL_H

#pragma once

#include "IRunLengthCodec.h"

/*
---------------------------------------------------------------------------
	Class definition.
---------------------------------------------------------------------------
*/
class InterPLastRunLevH263Impl : public IRunLengthCodec
{
public:
	InterPLastRunLevH263Impl(void);
	virtual ~InterPLastRunLevH263Impl(void);

// Interface implementation.
public:
	/** Encode the input to a run-length structure.
	Encode the input 2-D 8x8 block of Dct coeffs into the
	output last-run-level struct list.
	@param in		:	Input 8x8 block.
	@param rle	:	Last-run-level struct generated by the encode.
	@return			: none.
	*/
	void Encode(void* in, void* rle);

	/** Decode a run-length struct to the output.
	Decode the input last-run-level struct list into the
	output 2-D 8x8 block of Dct coeffs.
	@param rle	:	Last-run-level struct to decode.
	@param out	:	Output 8x8 block generated by the decode.
	@return			: none.
	*/
	void Decode(void* rle, void* out);

	void SetMode(int mode)	{ }
	int  GetMode(void)			{ return(0); }

// Class constants.
protected:
	static const int zigZagPos[64];

};// end class InterPLastRunLevH263Impl.

#endif	//_INTERPLASTRUNLEVH263IMPL_H
